---
title: "título do relatório."
author: ""
date: ""
output: 
  html_document:
    highlight: espresso
    theme: united
---
#### `r format(Sys.Date(), '%d-%b-%Y')`. 
```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(lubridate)
library(forcats)
library(DT)
library(glue)

Sys.setlocale(category = "LC_ALL")
options(scipen = 999)

# Carregando os dados no chunk global para poder ser compartilhada com todos # # usuários.

# Sempre haverá data frames, gráficos e outros objetos, vou deixar indicado.  
# df_01 <- read_rds("???.rds")
# 
# graf_01 <- df_01 %>% ???
# 
# objeto_01 <- df_01 %>% ???
#   
# objeto_02 <- df_01 %>% ???  
#   
# Etc...  

# Baixando a fonte Ubuntu.
library(showtext)
# Loading Google fonts (https://fonts.google.com/)
font_add_google("Ubuntu", "ubuntu")

# Automatically use showtext to render text
showtext_auto()

```
## {.tabset .tabset-pills}
### __1º item__.

#### Blá blá blá. 
#### Blá blá blá Blá blá blá.
>### Blá blá blá.Blá blá blá.Blá blá blá.

```{r, echo=FALSE, message=FALSE, fig.height=4, fig.width=9}

# Deixo abaixo os scripts que costumam ser mais trabalhosos.
# Lembrando a cor Ubuntu e os detalhes do geom_text.
  geom_col(fill = "#dd4814") + 
  
  # Aqui os textos estão na mesma altura e lado a lado, vjust iguais.
  geom_text(aes(label = prettyNum(round(variavel_01, 1),
  decimal.mark = ",")), vjust = -0.3, hjust = 1.5, size=10, family="ubuntu") +
  geom_text(aes(label = paste0("(", prettyNum(round(variável_02, 1),
  decimal.mark = ","), "%)")), vjust = -0.3, hjust = 0, size=10,  family="ubuntu") +
  
  # Aqui os textos estão um sobre o outro, hjust iguais.
  geom_text(aes(label = prettyNum(round(variavel_03, 3), decimal.mark = ",")),  vjust = -1.8, hjust = 0.5,   family="ubuntu", size=10) +
  geom_text(aes(label = glue('{prettyNum(round(variavel_04*100/arrec_tot, 1), decimal.mark=",")}%')), vjust = -0.2, hjust = 0.5, family="ubuntu", size=10)
  
 # Para realçar o eixo dos x. 
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
   
  theme(
    
    #Text format:
    #This sets the font, size, type and colour of text for the chart's title
    plot.title = element_text(family="ubuntu",
                                       size=30,
                                       face="bold",
                                       color="#222222"),
    #This sets the font, size, type and colour of text for the chart's   subtitle, as well as setting a margin between the title and the subtitle
    plot.subtitle = element_text(family="ubuntu",
                                          size=22,
                                          margin=margin(9,0,9,0)),
    plot.caption = element_text(family="ubuntu",
                                         size=12),
    
    # Não gosto de legenda, então vou comentar (retirar) a do bbc_style e 
    # colocar legend.position = "none"
    #Legend format
    #This sets the position and alignment of the legend, removes a title and backround for it and sets the requirements for any text within the legend. The legend may often need some more manual tweaking when it comes to its exact position based on the plot coordinates.
    # legend.position = "top",
    # legend.text.align = 0,
    # legend.background = element_blank(),
    # legend.title = element_blank(),
    # legend.key = element_blank(),
    # legend.text = element_text(family=font,
    #                                     size=18,
    #                                     color="#222222"),
    legend.position = "none",
    
    
    #Axis format
    #This sets the text font, size and colour for the axis test, as well as setting the margins and removes lines and ticks. In some cases, axis lines and axis ticks are things we would want to have in the chart - the cookbook shows examples of how to do so.
    axis.title = element_blank(),
    axis.text = element_text(family="ubuntu",
                                      size=25,
                                      color="#222222"),
    axis.text.x = element_text(margin=margin(5, b = 10)),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    
    # Também acho que valores no eixo y poluem o gráfico.
    # Retirá-los-ei do gráfico.
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    
    #Grid lines
    #This removes all minor gridlines and adds major y gridlines. In many cases you will want to change this to remove y gridlines and add x gridlines. The cookbook shows you examples for doing so
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color="#cbcbcb"),
    panel.grid.major.x = element_blank(),
    
    #Blank background
    #This sets the panel background as blank, removing the standard grey ggplot background colour from the plot
    panel.background = element_blank(),
    
    #Strip background (#This sets the panel background for facet-wrapped plots to white, removing the standard grey ggplot background colour and sets the title size of the facet-wrap title to font size 22)
    strip.background = element_rect(fill="white"),
    strip.text = element_text(size  = 22,  hjust = 0)
  )

```

### __2º item DT__.

#### Blá blá blá. 
#### Blá blá blá Blá blá blá.
>### Blá blá blá.Blá blá blá.Blá blá blá.

```{r, echo=FALSE, message=FALSE, fig.height=4, fig.width=9}

   datatable(filter = 'none',
              rownames = FALSE, class = 'cell-border stripe',
              colnames = c('der', 'fgty', 'nbjgu', 'nbjifu%'),
              options = list(bPaginate = TRUE)) %>%
  formatCurrency(3,
  currency = "",
  interval = 3,
  mark = "",
  digits = 3,
  dec.mark = ",",
  before = TRUE) %>%
  formatPercentage(columns = 4, digits = 1, mark = ",") %>% 
  formatStyle(columns = 1:4, fontSize = '125%')
  
```

### __3º item__.

#### Blá blá blá. 
#### Blá blá blá Blá blá blá.
>### Blá blá blá.Blá blá blá.Blá blá blá.

```{r, echo=FALSE, message=FALSE, fig.height=4, fig.width=9}

# Deixo abaixo os scripts que costumam ser mais trabalhosos.
# Lembrando a cor Ubuntu e os detalhes do geom_text.
  geom_col(fill = "#dd4814") + 
  
   # Aqui os textos estão na mesma altura e lado a lado, vjust iguais.
  geom_text(aes(label = prettyNum(round(variavel_01, 1),
  decimal.mark = ",")), vjust = -0.3, hjust = 1.5, size=10, family="ubuntu") +
  geom_text(aes(label = paste0("(", prettyNum(round(variável_02, 1),
  decimal.mark = ","), "%)")), vjust = -0.3, hjust = 0, size=10,  family="ubuntu") +
  
  # Aqui os textos estão um sobre o outro, hjust iguais.
  geom_text(aes(label = prettyNum(round(variavel_03, 3), decimal.mark = ",")),  vjust = -1.8, hjust = 0.5,   family="ubuntu", size=10) +
  geom_text(aes(label = glue('{prettyNum(round(variavel_04*100/arrec_tot, 1), decimal.mark=",")}%')), vjust = -0.2, hjust = 0.5, family="ubuntu", size=10)
  
 # Para realçar o eixo dos x. 
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
   
  theme(
    
    #Text format:
    #This sets the font, size, type and colour of text for the chart's title
    plot.title = element_text(family="ubuntu",
                                       size=30,
                                       face="bold",
                                       color="#222222"),
    #This sets the font, size, type and colour of text for the chart's subtitle, as well as setting a margin between the title and the subtitle
    plot.subtitle = element_text(family="ubuntu",
                                          size=22,
                                          margin=margin(9,0,9,0)),
    plot.caption = element_text(family="ubuntu",
                                         size=12),
    
    # Não gosto de legenda, então vou comentar (retirar) a do bbc_style e 
    # colocar legend.position = "none"
    #Legend format
    #This sets the position and alignment of the legend, removes a title and backround for it and sets the requirements for any text within the legend. The legend may often need some more manual tweaking when it comes to its exact position based on the plot coordinates.
    # legend.position = "top",
    # legend.text.align = 0,
    # legend.background = element_blank(),
    # legend.title = element_blank(),
    # legend.key = element_blank(),
    # legend.text = element_text(family=font,
    #                                     size=18,
    #                                     color="#222222"),
    legend.position = "none",
    
    
    #Axis format
    #This sets the text font, size and colour for the axis test, as well as setting the margins and removes lines and ticks. In some cases, axis lines and axis ticks are things we would want to have in the chart - the cookbook shows examples of how to do so.
    axis.title = element_blank(),
    axis.text = element_text(family="ubuntu",
                                      size=25,
                                      color="#222222"),
    axis.text.x = element_text(margin=margin(5, b = 10)),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    
    # Também acho que valores no eixo y poluem o gráfico.
    # Retirá-los-ei do gráfico.
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    
    #Grid lines
    #This removes all minor gridlines and adds major y gridlines. In many cases you will want to change this to remove y gridlines and add x gridlines. The cookbook shows you examples for doing so
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color="#cbcbcb"),
    panel.grid.major.x = element_blank(),
    
    #Blank background
    #This sets the panel background as blank, removing the standard grey ggplot background colour from the plot
    panel.background = element_blank(),
    
    #Strip background (#This sets the panel background for facet-wrapped plots to white, removing the standard grey ggplot background colour and sets the title size of the facet-wrap title to font size 22)
    strip.background = element_rect(fill="white"),
    strip.text = element_text(size  = 22,  hjust = 0)
  )

  
```

